repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.0.1'
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/pycqa/pylint
    rev: v2.16.2
    hooks:
    -   id: pylint
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
- repo: local
  hooks:
  -   id: pytest-check
      name: pytest-check
      entry: venv/bin/pytest
      language: system
      pass_filenames: false
      always_run: true
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.4'
  hooks:
  -   id: bandit
      exclude: ^tests/
      args:
        - -s
        - B101
